### ISSUE TITLE
Tweak the date of an event 

### ISSUE THREAD

**Issue by paulgoetze** [Zahnstochermann/whatsupin#13]
For a quick decision, whether an event is interesting for me it it helpful to also see the day of the week, 
e.g. **Mo, 06.06. 2016** instead of just **06.06. 2016** 

Also month names could read better than the number, e.g. **06. Jun 2016** instead of **06.06. 2016**

**Comment by paulgoetze** [comment]
@Zahnstochermann: looks nice! So I guess this one can be closed?

**Comment by Zahnstochermann** [comment]
yup
